### PR TITLE
[TrayStatus] update to 4.2

### PR DESCRIPTION
**Pull request by virtualex-itv**

### CODE REVIEW

**Comment by bc3tech** [comment]
@virtualex-itv seems like you must've submitted this but also took over ownership and pushed your own version of 4.2 to the community respository?

image

please do one or the other. If you don't want to keep the source here and contrib back to rely on my CI/CD to push the pkg, then don't submit duplicate updates to the repo here.

**Comment by virtualex-itv** [comment]
@bc3tech I submitted the pull request so you can update your source but didn’t make
any changes to the original repo. Simply submitted the updated package
after the pull request.  I reached out to you regarding v4.1 on how you’d
like me to submit an update but you never responded so I took the
initiative to update to 4.2 and sent a pull while I then pushed it out to
chocolatey.  Going forward I’ll just submit a pull and wait for you to use
your pipeline to push it out

**Comment by bc3tech** [comment]
Where did you reach out to me? I must have missed it?

4.1 was updated already via [another pull request](https://github.com/bc3tech/chocolatey/pull/4) ...

**Comment by virtualex-itv** [comment]
@bc3tech No worries.  I used the "Contact Maintainers" link on Chocolatey when 4.1 came out.  Then I saw that it was updated, so when 4.2 dropped, I updated and sent this pull request but had also pushed to chocolatey as I didn't know you used a CI/CD method for pushing it out.

**Pull request merged**
