### PR TITLE
Added System level flag

### LINKED ISSUE #1: Vivaldi Installation doesn't install in the system location
Hi, the Vivaldi package installs the program for a single user ("C:\Users\USER\AppData\Local\Vivaldi\Application\") instead of installing for the entire PC. It seems that the install argument `--system-level` isn't included in the installation command when running the package. The way I've had to make it install on the system level is running this command: `choco install vivaldi --install-arguments="--system-level"`. I wish this was included in the package installation since it's a bit inconvenient to remember every time I need to install it on multiple machines. Thanks

### PR DESCRIPTION
**Pull request by NovaViper**
Attempt to fix #1

### CODE REVIEW

**Comment by bc3tech** [comment]
Thanks for the contribution!

Unfortunately, this takes away the ability for Vivaldi to be installed per-user. Typically what we do here is create one portable pkg (i.e. `vivaldi.portable`) and one system pkg (i.e. `vivaldi.installer`) then a "meta" pkg (i.e. `vivaldi`) that defaults to either of those (portable in this case to maintain bkward compatibility.

See [my TrayStatus pkg](https://github.com/bc3tech/chocolatey/tree/master/TrayStatus) as an example and [this chocolatey documentation](https://chocolatey.org/docs/chocolatey-faqs#what-distinction-does-chocolatey-make-between-an-installable-and-a-portable-application) as well as [this post](http://ferventcoder.com/archive/2012/02/25/chocolatey---guidance-on-packaging-apps-with-both-an-install.aspx) on Rob's blog for more info

**Comment by NovaViper** [comment]
@bc3tech Ah ok. But the issue is there is no system level package for Vivaldi. This is particularly confusing since Chocolatey handles everything on the system level.

**Comment by bc3tech** [comment]
> Chocolatey handles everything on the system level.

not entirely accurate. You can, and many enterprises do, [install choco at a user-level with non-admin permissions](https://chocolatey.org/docs/installation#non-administrative-install) ([more here](https://chocolatey.org/docs/security#what-about-a-non-administrative-installation-of-chocolatey-is-it-secure)). This is why portable packages are important.

**Comment by bc3tech** [comment]
to install system-wide now, use `choco install vivaldi.install` and with the next vivaldi version, `vivaldi` will auto-install `vivaldi.portable`

~~~
2019-10-25T22:10:59.8408762Z Chocolatey v0.10.15
2019-10-25T22:11:56.4948302Z Attempting to push vivaldi.2.9.1705.4-snapshot.nupkg to https://push.chocolatey.org
2019-10-25T22:11:56.9368654Z An error has occurred. It's possible the package version already exists on the repository.
2019-10-25T22:11:57.4642210Z Chocolatey v0.10.15
2019-10-25T22:11:58.1203523Z Attempting to push vivaldi.install.2.9.1705.4-snapshot.nupkg to https://push.chocolatey.org
2019-10-25T22:14:23.9039197Z vivaldi.install 2.9.1705.4-snapshot was pushed successfully to https://push.chocolatey.org
2019-10-25T22:14:24.3862902Z Chocolatey v0.10.15
2019-10-25T22:14:25.0701569Z Attempting to push vivaldi.portable.2.9.1705.4-snapshot.nupkg to https://push.chocolatey.org
2019-10-25T22:15:00.4911431Z vivaldi.portable 2.9.1705.4-snapshot was pushed successfully to https://push.chocolatey.org
~~~

👍

**Pull request merged**
